# Generated by Django 4.2.4 on 2023-09-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0003_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='locations',
        ),
    ]
