# Generated by Django 4.2.4 on 2023-09-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0004_rename_location_user_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='locations',
            new_name='location',
        ),
    ]
