# Generated by Django 4.2.4 on 2023-09-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0005_rename_locations_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='locations',
        ),
    ]
