# Generated by Django 4.2.4 on 2023-08-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ads_id_alter_ads_price_alter_categories_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='is_published',
            field=models.CharField(max_length=100),
        ),
    ]
