# Generated by Django 4.2.4 on 2023-08-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ads_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='is_published',
            field=models.CharField(default='false', max_length=100),
        ),
    ]
