# Generated by Django 4.2.4 on 2023-10-09 10:25

from django.db import migrations, models
import loc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('member', 'Пользователь'), ('admin', 'Админ'), ('moderator', 'Модератор')], default='member', max_length=12)),
                ('age', models.IntegerField(null=True)),
                ('locations', models.CharField(verbose_name=loc.models.Location)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
