# Generated by Django 4.2.4 on 2023-10-13 12:51

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0001_initial'),
        ('user', '0002_remove_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='1992-08-06', validators=[user.validators.check_date_for_user]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[user.validators.check_email_for_user]),
        ),
        migrations.RemoveField(
            model_name='user',
            name='locations',
        ),
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(to='loc.location'),
        ),
    ]
