# Generated by Django 4.2.4 on 2023-10-13 12:52

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_birth_date_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[user.validators.check_email_for_user]),
        ),
    ]
